### ISSUE TITLE
extragas

### ISSUE THREAD

**Issue by walruzperil** [clovisjohn/opensea-sniper-bot#1]
Hello! Thx for your greate scripts. Since opensea-js updated stop working --extragas, they remove thins function.. Maybe you know how increase Gwei?

**Comment by clovisjohn** [comment]
which error are you getting?

**Comment by walruzperil** [comment]
no error, but gas not increase. opensea-js remove gas since eip1559...

**Comment by GwenBFX** [comment]
hey, did u find a fix to this issue? This doesn't increase here too.

**Comment by clovisjohn** [comment]
issue fixed
in 1.1.12+ versions of opensea-js, the ability to customize gas prices was removed
I have set-upped the bot to use the 1.1.11 version of opensea-js so it should work now
